version: "3.1"

services:
  postgresserver:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  backend:
    build: backend
    volumes:
      - ./backend/src:/project/src
    restart: on-failure
    ports:
      - 8000:80

volumes:
  db-data:
