version: "3.1"

services:
  postgresserver:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    command:
      - /bin/sh
      - -c
      - |
        yarn install
        yarn run dev --host 0.0.0.0
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build: backend
    volumes:
      - ./backend/src:/project/src
    restart: on-failure

volumes:
  db-data:
